# Generated by Django 4.2 on 2023-12-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
