# Generated by Django 4.2 on 2023-12-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='verify',
        ),
    ]
